### ISSUE TITLE
Getting an error sometimes in the console

### ISSUE THREAD

**Issue by Abwasserrohr** [Abwasserrohr/SKYBLOCK.SK#310]
```
[05:32:25] [pool-19-thread-7/ERROR]: #!#! Current item: set {_loc}(as java.lang.Object) to the location of (the block (at the location at ({_x}(as java.lang.Number), {SB::config::height}(as java.lang.Number), {_z}(as java.lang.Number)) in "%the world of {_l}(as java.lang.Object)%" parsed as a world >> ch.njol.skript.expressions.ExprBlock$1@57f1bec: org.bukkit.Location->org.bukkit.block.Block))->org.bukkit.Location
[05:32:25] [pool-19-thread-2/ERROR]: #!#! Current item: set {_loc}(as java.lang.Object) to the location of (the block (at the location at ({_x}(as java.lang.Number), {SB::config::height}(as java.lang.Number), {_z}(as java.lang.Number)) in "%the world of {_l}(as java.lang.Object)%" parsed as a world >> ch.njol.skript.expressions.ExprBlock$1@57f1bec: org.bukkit.Location->org.bukkit.block.Block))->org.bukkit.Location
[05:32:25] [pool-19-thread-7/ERROR]: #!#! Current trigger: function getcurrentbedrockmain (simple event) (checkislandaccess.sk, line -1)
[05:32:25] [pool-19-thread-2/ERROR]: #!#! Current trigger: function getcurrentbedrockmain (simple event) (checkislandaccess.sk, line -1)
```

```

[05:23:35] [pool-19-thread-3/ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:182)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[05:23:35] [pool-19-thread-9/ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:182)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[05:23:39] [pool-19-thread-7/ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:182)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[05:23:39] [pool-19-thread-5/ERROR]: #!#! 
[05:23:39] [pool-19-thread-5/ERROR]: #!#! [Skript] Severe Error:
[05:23:39] [pool-19-thread-5/ERROR]: #!#! 
[05:23:39] [pool-19-thread-5/ERROR]: #!#! Something went horribly wrong with Skript.
[05:23:39] [pool-19-thread-5/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[05:23:39] [pool-19-thread-5/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[05:23:39] [pool-19-thread-5/ERROR]: #!#! Following plugins are probably related to this error in some way:
[05:23:39] [pool-19-thread-5/ERROR]: #!#! SkQuery 
[05:23:39] [pool-19-thread-5/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[05:23:39] [pool-19-thread-5/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[05:23:39] [pool-19-thread-5/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[05:23:39] [pool-19-thread-5/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[05:23:39] [pool-19-thread-5/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[05:23:39] [pool-19-thread-5/ERROR]: #!#! 
[05:23:39] [pool-19-thread-5/ERROR]: #!#! Stack trace:
[05:23:39] [pool-19-thread-5/ERROR]: #!#! java.util.NoSuchElementException
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at java.util.LinkedList.removeFirst(LinkedList.java:270)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at java.util.LinkedList.pop(LinkedList.java:801)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.log.HandlerList.remove(HandlerList.java:40)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.log.SkriptLogger.removeHandler(SkriptLogger.java:111)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.log.LogHandler.stop(LogHandler.java:43)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.log.ParseLogHandler.printLog(ParseLogHandler.java:81)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:182)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:60)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.expressions.ExprLocationAt.get(ExprLocationAt.java:72)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.expressions.ExprLocationAt.get(ExprLocationAt.java:1)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.util.Direction$1.get(Direction.java:387)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.util.Direction$1.get(Direction.java:1)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.util.ConvertedExpression.getArray(ConvertedExpression.java:159)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.util.ConvertedExpression.getArray(ConvertedExpression.java:159)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.expressions.base.WrapperExpression.get(WrapperExpression.java:92)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:278)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:93)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:119)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:204)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.function.ExprFunctionCall.get(ExprFunctionCall.java:44)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:161)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:156)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.lambda$0(CondCompare.java:254)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:173)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:161)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:253)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:51)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:93)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:119)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:204)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.function.ExprFunctionCall.get(ExprFunctionCall.java:44)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:161)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:156)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.lambda$0(CondCompare.java:254)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:173)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:161)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:253)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:51)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:93)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:119)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:204)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:53)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at com.w00tmast3r.skquery.elements.effects.EffOptionThread$2.call(EffOptionThread.java:62)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at com.w00tmast3r.skquery.elements.effects.EffOptionThread$2.call(EffOptionThread.java:59)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[05:23:39] [pool-19-thread-5/ERROR]: #!#! 
[05:23:39] [pool-19-thread-5/ERROR]: #!#! Version Information:
[05:23:39] [pool-19-thread-5/ERROR]: #!#!   Skript: 2.3.6 (latest)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     Flavor: skriptlang-github
[05:23:39] [pool-19-thread-5/ERROR]: #!#!     Date: 2019-03-03
[05:23:39] [pool-19-thread-5/ERROR]: #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
[05:23:39] [pool-19-thread-5/ERROR]: #!#!   Minecraft: 1.13.2
[05:23:39] [pool-19-thread-5/ERROR]: #!#!   Java: 1.8.0_171 (Java HotSpot(TM) 64-Bit Server VM 25.171-b11)
[05:23:39] [pool-19-thread-5/ERROR]: #!#!   OS: Linux amd64 3.16.0-6-amd64
[05:23:39] [pool-19-thread-5/ERROR]: #!#! 
[05:23:39] [pool-19-thread-5/ERROR]: #!#! Server platform: Paper
[05:23:39] [pool-19-thread-5/ERROR]: #!#! 
[05:23:39] [pool-19-thread-5/ERROR]: #!#! Current node: null
[05:23:39] [pool-19-thread-5/ERROR]: #!#! Current item: set {_loc}(as java.lang.Object) to the location of (the block (at the location at ({_x}(as java.lang.Number), {SB::config::height}(as java.lang.Number), {_z}(as java.lang.Number)) in "%the world of {_l}(as java.lang.Object)%" parsed as a world >> ch.njol.skript.expressions.ExprBlock$1@57f1bec: org.bukkit.Location->org.bukkit.block.Block))->org.bukkit.Location
[05:23:39] [pool-19-thread-5/ERROR]: #!#! Current trigger: function getcurrentbedrockmain (simple event) (checkislandaccess.sk, line -1)
[05:23:39] [pool-19-thread-5/ERROR]: #!#! 
[05:23:39] [pool-19-thread-5/ERROR]: #!#! Thread: pool-19-thread-5
[05:23:39] [pool-19-thread-5/ERROR]: #!#! 
[05:23:39] [pool-19-thread-5/ERROR]: #!#! Language: english
[05:23:39] [pool-19-thread-5/ERROR]: #!#! Link parse mode: DISABLED
[05:23:39] [pool-19-thread-5/ERROR]: #!#! 
[05:23:39] [pool-19-thread-5/ERROR]: #!#! End of Error.
[05:23:39] [pool-19-thread-5/ERROR]: #!#! 
```

Everything still works, just the errors should be fixed, if possible.

**Comment by Abwasserrohr** [comment]
Maybe, this change has fixed this issue, if it still is an issue, it can be reopened later. https://github.com/Abwasserrohr/SKYBLOCK.SK/commit/aeee5f70eaf5e56ffd19299ba990963a683eb216
